### ISSUE TITLE
Nit: Consider Renaming Classes

### ISSUE THREAD

**Issue by Keepingshtum** [vsawce/CS151-GitCommitDie#1]
It's not immediately obvious that "Post" and "User" are actually handlers to help with post and comment CRUD actions - may I suggest using something like PostService or PostHandler instead?

Good presentation of diagrams. 

(If you're wondering what a nit is, [here's a cool link](https://josipmisko.com/posts/code-review-nit).)

You may proceed to implementation without addressing this issue since it is just a nit. Whichever you choose, leave a response below and close the issue once it is addressed.

**Comment by vsawce** [comment]
We are treating Post as its own object which provides CRUD for its inherited classes as well as its own appropriate data members.

Page is essentially supposed to serve as the "PostHandler" instead.

Please feel free to let us know if you have any questions or concerns!
